# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Uninstall AWS CLI
        run: |
          sudo rm /usr/local/bin/aws
          sudo rm /usr/local/bin/aws_completer
          sudo rm -rf /usr/local/aws-cli
      # - name: Verify that AWS CLI is not installed
      #   run: |
      #     if output=$(aws --version); then
      #         echo "AWS installed"
      #     else
      #         echo "AWS removed"
      #         exit 1
      #     fi
      # Refer to https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
      - name: Setting up AWS CLI
        run: |
          ls
          # unzip ./aws-cli.zip
          # cp ./aws-cli /usr/local/aws-cli
          # rm -rf ./aws-cli
          cp ./aws /usr/local/bin/aws
          cp ./aws_completer /usr/bin/aws_completer
      - name: Verify AWS CLIE installation 
        run: |
          aws --version
